import * as fs from 'fs';
import yargs from 'yargs';

let input;
let output;
let watch;

try {
  const argv = yargs(process.argv.slice(2)).argv;
  input = argv.input ?? './TailwindGenerated.css';
  output = argv.output ?? './ReadyForLitimport.js';
  watch = argv.watch ?? false;
} catch (e) {
  console.log(`Incorrect arguments provided. Please provide input and output file paths.`);
}

function parse() {
  let contents;

  try {
    contents = fs.readFileSync(input, 'utf8');
  } catch (e) {
    console.log(`Failed to read file ${input}. Might just not be created yet? retrying..`);
  }

  let cleanContents = contents.replaceAll('`', '').replaceAll('\\', '\\\\');

  const litContents = `
    /* DO NOT EDIT THIS FILE. This file has been generated with tw2lit.js */
    import { css } from "lit";
    export const TWStyles = css\` ${cleanContents} \`
    `;

  fs.writeFileSync(output, litContents);
  console.log(`tw2lit - conversion complete`);
}

if (watch) {
  fs.watchFile(input, { interval: 1000 }, () => {
    try {
      parse();
    } catch (err) {
      console.log(err);
    }
  });
} else {
  try {
    parse();
  } catch (err) {
    console.log(err);
  }
}
